[features]
seeds = false

[programs.localnet]
first_nft = "J6L2xrww6gBjw7cVaAhUNEHQHFX8wM57ph4TBcTAF3v9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/anj_powr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
